## Platform = {android, ios, browser_stack}
Platform=android

# Grid Specific
AppiumServer=http://127.0.0.1:4723/wd/hub

# Test Data Specific
TCIDColumn=TC_ID
RunmodeColumn=RunMode
#TestDataExcelFileName=TestDataSelendroid.xlsx
TestDataExcelFileName=WhereIsMyTrain.xlsx
#RunModeSheetName=Registration
TestDataSheetName=Reg
RunModeSheetName=Sheet1

# App Info for Local Android
#AppName=TestApp.apk
AppName=Where is my Train.apk
AutomationName=uiautomator2
DeviceName=M2003J6B1l
#DeviceName=Nexus_5X
UDID=8fc3ecc0
#UDID=86bf1ba7s
#UDID=emulator-5554
PlatformVersion=12
#PlatformVersion=11.0
#AppPackage=com.paytm.paytmplay
#AppPackage=io.selendroid.testapp
AppPackage=com.whereismytrain.android
#AppActivity=com.gamepind.login.ui.LoginActivity
#AppActivity=io.selendroid.testapp.HomeScreenActivity
AppActivity=com.whereismytrain.view.activities.HomeActivity
NoReset=true
AutoGrantPermissions=true

# App Info for Local iOS

# App Info for BrowserStack/ Cloud
CloudDeviceName=Google Nexus 6
CloudPlatformVersion=6.0


# General Settings
Timeout=20

# Credentials
UserName=
Password=

#Extent Report
Environment=Staging
TeamName=Test team

# BrowserStack Credentials
bsUserName=
bsAccessKey=
bsAppHash=